name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build and Push API Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/api:latest ./sdv-api
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/api:latest

      - name: Build and Push Web Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/web:latest ./sdv-web
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/web:latest
